### PR TITLE
feat: add get project install config endpoint

### PR DESCRIPTION
**Pull request by MichaelGoberling**
## Description

Add the new endpoint for fetching a project's install config 

See Transporter API docs: https://developers.corp.adobe.com/adobeio/transporter/transporterSwagger.json#tag/Data/paths/~1console~1data~1projects~1{projectId}~1install-config/get

## Motivation and Context

Allow template registry service to copy the install config for a given project

## How Has This Been Tested?

Locally linked package, `npm run test`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by arjuncooliitr — APPROVED** [review]
LGTM

**Review by moritzraho — APPROVED** [review]
👍 👍

**Comment by shazron** [comment]
Was this just a drop-in from their OpenAPI spec or you had to copy and paste this in?

**Comment by MichaelGoberling** [comment]
@shazron 

This was a copy and paste, I originally did a full copy but there were a lot more changes than I expected, including some changes to existing paths that might've been breaking. Should we create a follow-up task to sync with the latest?

**Comment by shazron** [comment]
@MichaelGoberling we've been doing patches for one-off additions: https://github.com/adobe/aio-lib-console/tree/master/spec/patch

**Comment by MichaelGoberling** [comment]
@shazron 
Ah, I see. I think the patch is needed for that one xr endpoint because it isn't in the Swagger definition. The endpoint I added as part of this PR is part of the Swagger, I just decided to forgo doing the full drop-in because it included more changes than I expected. Let me try to do the full drop-in and do some testing on this PR

**Review by shazron — APPROVED** [review]

**Pull request merged**
