### PR TITLE
Stage env api is console-devall

### PR DESCRIPTION
**Pull request by purplecabbage**
console-stage will likely only ever be used by the console team.

### CODE REVIEW

**Comment by moritzraho** [comment]
Thanks Jesse, thought console was going to push xt reg changes to stage at some point ?
Otherwise pr lgtm (just added a commit to also update the transporter api endpoint) feel free to merge this

**Comment by shazron** [comment]
@purplecabbage is this PR still valid?

**Comment by purplecabbage** [comment]
Need some input from @maverickmishra or someone on console team

**Comment by purplecabbage** [comment]
Spoke with Roman, the stage url is fine, the other is a dev url.

**Pull request closed without merging**
